const accountConfigRender = require('../controllers/getControllers/accountConfigRender')
const cuentaRender = require('../controllers/getControllers/accountRender')
const balanceRender = require('../controllers/getControllers/balanceRender')
const updateEmailClient = require('../controllers/getControllers/updateEmailClient')
const { updatePasswordClient } = require('../controllers/postControllers/updateClient')
const { updateEmail } = require('../controllers/postControllers/updateEmail')
const { validateClientAccount } = require('../middlewares/validateClientAccount')
const { validateEmail } = require('../middlewares/validateEmailClient')
const verifiedEmailExist = require('../middlewares/verifiedEmailExist')
const router = require('express').Router()
router.get('/cuenta',cuentaRender)
router.get('/accountSetting',accountConfigRender)
router.get('/balance',balanceRender)
router.get('/updateEmailClient',updateEmailClient)
router.post('/cuenta',validateClientAccount,updatePasswordClient)
router.post('/updateEmailClient',validateEmail,verifiedEmailExist,updateEmail)
module.exports = router