const forgotPasswordRender = require('../controllers/getControllers/forgotPasswordRender')
const loginRender = require('../controllers/getControllers/loginRender')
const singUpRender = require('../controllers/getControllers/singUpRender')
const loginUser = require('../controllers/postControllers/loginUser')
const registerUser = require('../controllers/postControllers/registerUser')
const sendNewPasswordToMail = require('../controllers/postControllers/sendNewPasswordToMail')
const logoutUser = require('../controllers/postControllers/logoutUser')
const { validateLoginForm } = require('../middlewares/validateLoginForm')
const { validateRegisterForm } = require('../middlewares/validateRegisterForm')
const verifiedIfUserAlreadyExits = require('../middlewares/verifiedIfUserAlreadyExits')
const validateCheckbox = require('../middlewares/validateCheckbox')
const router = require('express').Router()
router.get('/login',loginRender)
router.get('/register',singUpRender)
router.get('/forgot-password',forgotPasswordRender)
router.post('/register',validateRegisterForm,verifiedIfUserAlreadyExits,validateCheckbox,registerUser)
router.post('/login',validateLoginForm,loginUser)
router.post('/forgot-password',sendNewPasswordToMail)
router.post('/logout',logoutUser)
module.exports =router