const forgotPasswordRender = require('../controllers/getControllers/forgotPasswordRender')
const loginRender = require('../controllers/getControllers/loginRender')
const singUpRender = require('../controllers/getControllers/singUpRender')
const loginUser = require('../controllers/postControllers/loginUser')
const registerUser = require('../controllers/postControllers/registerUser')
const sendNewPasswordToMail = require('../controllers/postControllers/sendNewPasswordToMail')
const logoutUser = require('../controllers/postControllers/logoutUser')
const router = require('express').Router()
router.get('/login',loginRender)
router.get('/register',singUpRender)
router.get('/forgot-password',forgotPasswordRender)
router.post('/register',registerUser)
router.post('/login',loginUser)
router.post('/forgot-password',sendNewPasswordToMail)
router.post('/logout',logoutUser)
module.exports =router