const addProductRender = require('../controllers/getControllers/addProductRender')
const addNewProduct = require('../controllers/postControllers/addNewProduct')
const getAllProducts = require('../controllers/getControllers/catalogRender')
const getProductById = require('../controllers/getControllers/getProductById')
const updateProductRender = require('../controllers/getControllers/updateProductRender')
const updateProduct = require('../controllers/postControllers/updateProduct')
const upload = require('../helpers/multer')
const router = require('express').Router()
router.get('/',getAllProducts)
router.get('/product/:id',getProductById)
router.get('/add-product',addProductRender)
router.get('/update-product/:id',updateProductRender)
router.post('/add-product',upload,addNewProduct)
router.post('/update-product',updateProduct)
module.exports =router