const addProductRender = require('../controllers/getControllers/addProductRender')
const addNewProduct = require('../controllers/postControllers/addNewProduct')
const getAllProducts = require('../controllers/getControllers/catalogRender')
const getProductById = require('../controllers/getControllers/getProductById')
const updateProductRender = require('../controllers/getControllers/updateProductRender')
const updateProduct = require('../controllers/postControllers/updateProduct')
const upload = require('../helpers/multer')
const validateAddProductForm = require('../middlewares/validateAddProductForm')
const deleteProduct = require('../controllers/postControllers/deleteProduct')
const listProducts = require('../controllers/getControllers/listProducts')
const { productFilter } = require('../controllers/postControllers/getProductsFilter')
const accountRender = require('../controllers/getControllers/accountRender')
const router = require('express').Router()
router.get('/',getAllProducts)
router.get('/product/:id',getProductById)
router.post('/filter',productFilter)
router.get('/add-product',addProductRender)
router.get('/update-product/',listProducts)
router.get('/update-product/:id',updateProductRender)
router.post('/add-product',upload,validateAddProductForm,addNewProduct)
router.post('/update-product',upload,updateProduct)
router.post('/delete',deleteProduct)
module.exports =router